# Generated by Django 2.2.16 on 2022-06-12 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.RenameField(
            model_name='Post',
            old_name='pub_date',
            new_name='created'
        )
        # migrations.RemoveField(
        #     model_name='post',
        #     name='pub_date',
        # ),
        # migrations.AddField(
        #     model_name='post',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='comments',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        # ),
    ]
